
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  elasticsearch:
    rest:
      uris: http://${GSE_ES_HOST:${es.host.ip}}:${GSE_ES_PORT:9800}
      username: ${ES_USER:elastic}
      password: ${ES_PASS:zGGKZUG4D34gdwkyPCtXCd4KU56b2XtA}
server:
  port: 8080